name: Spam Classifier Training

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    services:
      mlflow-server:
        image: ghcr.io/mlflow/mlflow
        ports:
          - 5000:5000
        env:
          MLFLOW_ARTIFACT_ROOT: ./mlruns
          MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas scikit-learn mlflow joblib

      - name: Create directories
        run: |
          mkdir -p mlruns
          touch mlflow.db

      - name: Verify spam.csv exists
        run: |
          if [ ! -f spam.csv ]; then
            echo "Error: spam.csv not found!"
            ls -la
            exit 1
          fi

      - name: Run training
        run: python train.py
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000

      - name: Verify output files
        run: |
          echo "Contents of working directory:"
          ls -la
          echo "Contents of mlruns:"
          ls -la mlruns/
          test -f spam_model.joblib || echo "Warning: spam_model.joblib not found"

      - name: Package artifacts
        run: |
          tar -czvf mlruns.tar.gz mlruns/
          tar -czvf model_files.tar.gz spam_model.joblib requirements.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            mlruns.tar.gz
            model_files.tar.gz
          retention-days: 5
