name: Train Spam Detector

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    services:
      mlflow-server:
        image: mlflow/mlflow
        ports:
          - 5000:5000
        env:
          MLFLOW_ARTIFACT_ROOT: ./mlruns
          MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
        options: --health-cmd "curl -f http://localhost:5000" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow sklearn pyarrow

      - name: Run training script
        run: |
          python train.py
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000

      - name: Archive and upload results
        run: |
          tar -czvf mlruns.tar.gz mlruns/
          tar -czvf model_artifacts.tar.gz spam_model.joblib
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: |
            mlruns.tar.gz
            model_artifacts.tar.gz
          retention-days: 7
